#-*-mode: makefile-*-

include $(SRCDIR)/makeincludes/Makeinclude.global


#
# Define vars used in Makeinclude.libs
#
LIB			= liblplib.a
CFILES 		= config_file.c    lpalias.c        misc.c           sender.c \
	lpglobals.c      newmail.c        signals.c \
	fio.c            lprevdbm.c       silp.c \
	file_list.c



include $(SRCDIR)/makeincludes/Makeinclude.libs
