#-*-mode: makefile-*-

include $(SRCDIR)/makeincludes/Makeinclude.global


#
# Define vars used in Makeinclude.libs
#
LIB			= libobjects.a
CFILES 		= message.c subscriber.c message_header.c subfile.c \
		  email_list.c mbox.c news.c peer.c


include $(SRCDIR)/makeincludes/Makeinclude.libs
