#-*-makefile-*-

include $(SRCDIR)/makeincludes/Makeinclude.global

TARGETS = list
CFILES = list.c processed_items.c list_utils.c list_mail_header.c \
	distribute.c list_globals.c digest.c list_file_archive.c \
	process_message.c moderate.c process_errors.c 
CHMOD = 

include $(SRCDIR)/makeincludes/Makeinclude.bins

