#! /bin/sh
#                          @(#)add	6.2 CREN 98/03/03
# 
#                         Copyright (c) 1993-98 by
#         the Corporation for Research and Educational Networking (CREN)
# 
# All rights reserved. This software comprises confidential
# information of CREN and may not be used, copied or made available to anyone,
# except in accordance with the license under which it is furnished.
# 



#! /bin/sh
cat <<EOF

A note on syntax:  

   * square bracktes ('[' and ']') indicate that the parameter is optional.  
   * angle brackets ('<' and '>') indicate that you should enter an 
     actual value

In BOTH cases, these brackets are used only to show how the command
works - they should not be added in actual commands sent to the
ListProc server.


Syntax: [quiet] add <list> <password> <address> <full name>
Syntax: [quiet] add <list> <password> {<address> <fullname>} {<address> <fullname>} ...

        Add a new user to the specified list, or a list of specified users.
        If quiet, the user(s) will not be notified.

        For example:

                quiet add ermis passwd foo@bar Foo Bar
                add ermis passwd {foo1@bar Foo1 Bar} {foo2@bar Foo2 Bar}

        Notice in the second example, the delimiting { and } are required.
EOF
