#! /bin/sh
#                          @(#)index	6.2 CREN 98/03/03
# 
#                         Copyright (c) 1993-98 by
#         the Corporation for Research and Educational Networking (CREN)
# 
# All rights reserved. This software comprises confidential
# information of CREN and may not be used, copied or made available to anyone,
# except in accordance with the license under which it is furnished.
# 
# SCCS file: /usr/SCCS/home/server/listproc/help/s.index
#


#! /bin/sh
cat <<EOF

A note on syntax:  

   * square bracktes ('[' and ']') indicate that the parameter is optional.  
   * angle brackets ('<' and '>') indicate that you should enter an 
     actual value

In BOTH cases, these brackets are used only to show how the command
works - they should not be added in actual commands sent to the
ListProc server.


Syntax: index [archive | path-to-archive] [/password] [-all]

        Get a list of files for the specified archive, or listproc -- the
        master archive, if none given. Files are actually listed for
        the requested archive, plus all of its subarchives but only if you
        provide the -all option. Obviously the master archive will list all
        of the available files from this server.

        Certain archives may be private, and in this case you have to
        specify a password for accessing them. The slash is required.
        Different archives may have different passwords.

        If you do not specify an archive but provide a password, then
        only public and private archives that match this password will
        be listed.

        The archiving system is hierarchical. Therefore subarchives
        may have the same names; they can be distinguished by the path
        (the branch in the hierarchy) to them. For example, the archives
        unix and pub/unix are distinct. 'path-to-archive' is a UNIX style
        path (such as pub/unix) -- i.e. a '/' is used to move through the
        branches of the hierarchy. An 'index' request always reports paths
        to archives for your convenience.
EOF
