#! /bin/sh
#                          @(#)purge	6.2 CREN 98/03/03
# 
#                         Copyright (c) 1993-98 by
#         the Corporation for Research and Educational Networking (CREN)
# 
# All rights reserved. This software comprises confidential
# information of CREN and may not be used, copied or made available to anyone,
# except in accordance with the license under which it is furnished.
# 
# SCCS file: /usr/SCCS/home/server/listproc/help/s.purge
#

#! /bin/sh
cat <<EOF

A note on syntax:  

   * square bracktes ('[' and ']') indicate that the parameter is optional.  
   * angle brackets ('<' and '>') indicate that you should enter an 
     actual value

In BOTH cases, these brackets are used only to show how the command
works - they should not be added in actual commands sent to the
ListProc server.


Syntax: purge <password>
Syntax: purge <password> <address> [address] ...

        If issued by a subscriber, it removes him/her from all local lists.
        <password> can be from any mailing list.

        If issued by the manager, it removes all the specified addresses
        from all local lists -- the system's password is required. All
        users are removed quietly.

        Examples:

                purge pass1
                purge system-password foo@bar.com user@host.domain
EOF
