#! /bin/sh
#                          @(#)statistics	6.2 CREN 98/03/03
# 
#                         Copyright (c) 1993-98 by
#         the Corporation for Research and Educational Networking (CREN)
# 
# All rights reserved. This software comprises confidential
# information of CREN and may not be used, copied or made available to anyone,
# except in accordance with the license under which it is furnished.
# 
# SCCS file: /usr/SCCS/home/server/listproc/help/s.statistics
#


#! /bin/sh
cat <<EOF

A note on syntax:  

   * square bracktes ('[' and ']') indicate that the parameter is optional.  
   * angle brackets ('<' and '>') indicate that you should enter an 
     actual value

In BOTH cases, these brackets are used only to show how the command
works - they should not be added in actual commands sent to the
ListProc server.


Syntax: statistics <list> {[subscriber email address(es)] | [-all]}

        Get statistical information for all subscribers, or for the specified
        one(s) only, in the specified list. Each email address is followed
        by a count of the number of messages sent to this list by this user
        to date. Wild characters are allowed when inquiring about specific
        subscribers. If the list is linked with other peer lists, your request
        will be forwarded to the appropriate server(s) also, except when the
        request is live.

        If you want statistics about all users to date (whether currently
        subscribed or not) that have posted messages on the list, provide the
        -all switch.

        If a list is private, members only may issue this request.
EOF
