#! /bin/sh
#                          @(#)system	6.2 CREN 98/03/03
# 
#                         Copyright (c) 1993-98 by
#         the Corporation for Research and Educational Networking (CREN)
# 
# All rights reserved. This software comprises confidential
# information of CREN and may not be used, copied or made available to anyone,
# except in accordance with the license under which it is furnished.
# 
# SCCS file: /usr/SCCS/home/server/listproc/help/s.system
#


#! /bin/sh
cat <<EOF

A note on syntax:  

   * square bracktes ('[' and ']') indicate that the parameter is optional.  
   * angle brackets ('<' and '>') indicate that you should enter an 
     actual value

In BOTH cases, these brackets are used only to show how the command
works - they should not be added in actual commands sent to the
ListProc server.


Syntax: system <list> <password> <address> #<user-request>

        Execute a request on behalf of another user address.

        For example:

                system ermis passwd foo@bar #subscribe ermis Foo Bar

        will subscribe address foo@bar to list ermis. And so will this:

                add ermis passwd foo@bar Foo Bar

        All restrictions are lifted while executing "system" requests.
EOF
