#! /bin/sh
#  			@(#)which-owned	6.2 CREN 98/03/03
# 
# 			Copyright (c) 1993-98 by
# 	the Corporation for Research and Educational Networking (CREN)
# 
# All rights reserved. This software comprises confidential information
# of CREN and may not be used, copied or made available to anyone,
# except in accordance with the license under which it is furnished.
# 
# SCCS file: /usr/SCCS/home/server/listproc/help/s.which-owned
#

#! /bin/sh
cat <<EOF
Syntax: which-owned

        Get a list of all mailing lists (served by this server) which
        you are the owner of.
EOF
