#-*-mode: makefile-*-


#######################################################################
#
# Nothing below should need to be modified.
#
#######################################################################

include $(SRCDIR)/makeincludes/Makeinclude.global


LIB		= libsend.a
CFILES 	= lpsmtp.c ucbmail.c utils.c  \
		  mtasend.c pipemail.c mail_queue.c \
		  smtpmail.c lpsend.c notify.c


include $(SRCDIR)/makeincludes/Makeinclude.libs

