
include $(SRCDIR)/makeincludes/Makeinclude.global


#######################################################################
#
# Nothing below should need to be modified.
#
#######################################################################

LIB 		= liblpport.a
CFILES 		= locks.c

include $(SRCDIR)/makeincludes/Makeinclude.libs




