/*
 *
 *   lptypes.h
 *
 *
 *   Definitions of useful data types and constants
 *   
 *
 */

#ifndef LPTYPES_H
#define LPTYPES_H

#include <string.h>

/*
 * End of string marker
 */
#undef EOS
#define EOS 0


/*
 * End of line stuff
 */
#define CRLF "\015\012"
#define CR '\015'
#define LF '\012'

/* return a pointer to the end of line character, or EOS */
#define end_of_line(pos)  (pos + strcspn(pos,CRLF))

/* return a pointer that is PAST the current CR, CRLF, or LF sequence */
#define skip_crlf(end)     (                      \
   (*end==CR && *(end+1)==LF) ? (end+2) :         \
      ((*end==CR || *end==LF) ? (end+1) : (end))  )


/*
 *  String stuff
 */

/* To accomodate different character sets, this should perhaps be
   automatically generated by an initial call to isspace() to set up a
   static string. */
extern char lptypes_whitespace[];
#define skip_whitespace(pos)  (pos + strspn(pos,lptypes_whitespace))
#define skip_non_whitespace(pos)  (pos + strcspn(pos,lptypes_whitespace))



/*
 * Boolean type
 */
#undef TRUE
#undef FALSE
typedef enum {
  FALSE=0,
  TRUE=1
} bool;

typedef bool BOOLEAN;



/*
 * Type for return values
 */
typedef enum {
  ERROR=-1,
  FAILURE=0,
  SUCCESS=1
} retval;


#endif /*LPTYPES_H*/

