#-*-mode: makefile-*-

include $(SRCDIR)/makeincludes/Makeinclude.global


#
# Define vars used in Makeinclude.libs
#
LIB			= liblputil.a
CFILES 		= \
lpconfig.c         lpexit.c           lpsetuid.c         regerror.c \
lpcounter_file.c   lpfile.c           lpsig.c            regex.c \
lpdir.c            lpinit.c           lpstring.c         regexp.c \
lperrmsg.c         lplock.c           lpsyslib.c         regsub.c \
lplog.c            mailrfc.c          string_table.c     lpexec.c \
plist.c            lpmd5.c            md5c.c             lptypes.c



include $(SRCDIR)/makeincludes/Makeinclude.libs


